export const REVIEW_STEP_NAMES = [
  'Product',
  'Release(s)',
  'Extras',
  'Languages',
  'Modes',
  'Accessibility',
  'Disclosures',
  'Literacy',
  'Mechanics',
  'Dynamics',
  'Aesthetics',
  'Summary',
  'Comments',
  'Title & Publish',
];
